/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.DaoFactory;
import DAO.EnseignantDAO;
import DAO.UserChecker;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import models.Enseignant;
import models.Matiere;

/**
 *
 * @author DIGITAL
 */
public class FrameLogin extends javax.swing.JFrame {
private DaoFactory daoFactory;
    /**
     * Creates new form FrameLogin
     */
    public FrameLogin(DaoFactory daoFactory) {
        initComponents();
        this.daoFactory = daoFactory;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Connexion");
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JTextField();
        btConnecter = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FrameLogin"); // NOI18N
        setType(java.awt.Window.Type.POPUP);

        jLabel2.setText("Mot de Passe");

        btConnecter.setText("Connecter");
        btConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnecterActionPerformed(evt);
            }
        });

        btCancel.setText("Annuler");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btConnecter)
                .addGap(62, 62, 62)
                .addComponent(btCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancel)
                    .addComponent(btConnecter))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConnecterActionPerformed
        // TODO add your handling code here:
        //connexion d'un enseignant
        if(!txtPwd.getText().equals(""))
        {
            UserChecker user = new UserChecker(this.daoFactory,"enseignants", txtPwd.getText());
            if(user.Check())
            {
                EnseignantDAO enseignantDao = new EnseignantDAO(this.daoFactory);
                Enseignant enseignant = null;
                enseignant = enseignantDao.find("password", txtPwd.getText());
                if(enseignant == null)
                {
                    (new Message("mot de passe incorrecte !")).setVisible(true);
                }
                else
                {
                    ArrayList<Matiere> mat = enseignant.getListMatiere();
                    FrameSaisieNote fsn = new FrameSaisieNote(daoFactory, enseignant);
                    fsn.setVisible(true);
                    this.dispose(); 
                }
                
            }
        }
        
    }//GEN-LAST:event_btConnecterActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btConnecter;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPwd;
    // End of variables declaration//GEN-END:variables
}
