/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.DaoFactory;
import DAO.EtudiantDAO;
import DAO.NoteDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.Enseignant;
import models.Etudiant;
import models.Matiere;

/**
 *
 * @author DIGITAL
 */
public final class FrameSaisieNote extends javax.swing.JFrame {
    private DaoFactory daoFactory;
    private Enseignant enseignant = null;
    public DefaultTableModel model;
    public ArrayList<Etudiant> listEtudiant;
    ArrayList<Matiere> listMatiere;
    Etudiant etudiant;
    float note;
    String matricule;
    /**
     * Creates new form SaisieNote
     * @param enseignant
     */
    public FrameSaisieNote(DaoFactory dao, Enseignant enseignant) {
        initComponents();
        this.daoFactory = dao;
        this.enseignant = enseignant;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //ArrayList<Matiere> listMatiere = new ArrayList<Matiere>();
        listMatiere = enseignant.getListMatiere();
        for(Matiere mat: listMatiere)
        {
           //System.out.println(mat.toString());
            System.out.println(mat.toString());
            comboMatiere.addItem(mat.getIntitule());
        }
        model = (DefaultTableModel) tblNote.getModel();
        addRowToJtableNote();
    }
   
    // charger la liste des etudiant dans le tableau pour la saisie des notes
    public void addRowToJtableNote()
    {
        //System.out.println(enseignant.toString());
        //String intitule = comboMatiere.getSelectedItem().toString();
        //String intitule = comboMatiere.getSelectedItem().toString();
        String intitule = "Analyse et Conception Orientée Objet";
        //HashMap ListNote = new HashMap();
        EtudiantDAO etudiantDao = daoFactory.getEtudiantDAO();
        //listEtudiant = new ArrayList();
        listEtudiant = etudiantDao.getAll();
        Object rowData[] = new Object[6];
        for(int i = 0; i < listEtudiant.size(); i++)
        {  
            rowData[0] = listEtudiant.get(i).getNom();
            rowData[1] = listEtudiant.get(i).getPrenom();
            rowData[2] = listEtudiant.get(i).getDate();
            rowData[3] = listEtudiant.get(i).getLieu();
            rowData[4] = listEtudiant.get(i).getMatricule();
            //afficher la note correspondante à la matiere dans la combo
            //comboMatiere.getSelectedItem().toString()
            rowData[5] = listEtudiant.get(i).getListNote().get(comboMatiere.getSelectedItem().toString());
            model.addRow(rowData);
        }
        
        
    } 
//    public void mouseClicked(MouseEvent evt)
//    {
////       tblNote.addMouseListener(new MouseAdpater(){
////       System.out.println("");
////       });
//        int row = tblNote.getSelectedRow();
//        int col = tblNote.getSelectedColumn();
//        float note = (float) model.getValueAt(row, col);
//        
//        
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNote = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        comboMatiere = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblNote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Date Naissance", "Lieu Naissance", "Matricule", "Note"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNote.setColumnSelectionAllowed(false);
        tblNote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNoteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNoteMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblNote);

        txtSearch.setText("Rechercher ici");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L3S6" }));

        jLabel1.setText("Niveau");

        jLabel2.setText("Matiere");

        jLabel3.setText("Note");

        txtNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoteActionPerformed(evt);
            }
        });

        btAdd.setText("Ajouter");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here
        //initialiser la combo liste des matiere de l'enseignant 
        
        
    }//GEN-LAST:event_formWindowActivated

    private void txtNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoteActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        int note = Integer.parseInt(txtNote.getText());
        if(txtNote.getText().equals("") || txtNote.getText().equals(null) || note<0)
        {
            Message m = new Message("valeur incorrecte !");
        }
        else
        {
            
            NoteDAO noteDao = daoFactory.getNoteDAO();
            for(Etudiant e : listEtudiant)
            {
                String var = e.getMatricule();
                if(var.equals(matricule))
                {
                 etudiant = e;
                 break;
                }
                
                
            }
            if(note>=0)
            {
                //mise à jour de la note
                noteDao.create(note,etudiant.getId());
                Message m = new Message("Enregistré !");
            }
            else
            {
                //creation d'une note
                noteDao.update(note,etudiant.getId());
                Message m = new Message("Enregistré !");
                
            }
            
        }
   
    }//GEN-LAST:event_btAddActionPerformed

    private void tblNoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNoteMousePressed
        // TODO add your handling code here:
        System.out.println("mouse pressed");
    }//GEN-LAST:event_tblNoteMousePressed

    private void tblNoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNoteMouseClicked
        // TODO add your handling code here:
        int var = 2;
        TableModel mod = tblNote.getModel();
        System.out.println("row count: "+ var);
        System.out.println("mouse click");
        int row = tblNote.getSelectedRow();
        System.out.println("row count: "+row);
        txtNote.setText(model.getValueAt(row, 5).toString());
        matricule = model.getValueAt(row, 4).toString();
        note = Float.valueOf(txtNote.getText());
        System.out.println("Ok");
    }//GEN-LAST:event_tblNoteMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameSaisieNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameSaisieNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameSaisieNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameSaisieNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameSaisieNote().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JComboBox<String> comboMatiere;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblNote;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
public static void main(String[] arg)
{
    System.out.println("coolest");
}

}
